version: "0.1.0"

services:
  cms:
    image: cyasam/aktif-strapi
    container_name: aktif-strapi
    env_file:
      - .env
    ports:
      - "1337:1337"
    volumes:
      - db-data:/opt/app/.tmp
volumes:
  db-data:
    driver: local
